#系统参数配置
mango:
  name: mango
  version: 1.0.0
  lexiconLoad: false  # false不加载词库
  cron: 0 46 11 * * ? #定时时间
  # 获取ip地址开关
  addressEnabled: false
  # 验证码开关
  captchaEnable: true
  #微信参数配置
  wxapp:
    #公众号
    gzh:
      appid: wxc9a4518ec83192f21 #测试号appid
      secret: c5f9f0943c897145dc39878761c6748b1 #测试号sercret
      #接口鉴权token
      token: qingtengpai
      #对象存储
    oss:
      secretId:
      secretKey:
      region: ap-nanjing
      bucketName:
      #微信小程序
    uniapp:
      appid:
      secret:
  #文件上传路径
  profile: D:/idea_demo/mango/upload
#服务配置
server:
  port: 5188
  tomcat:
    accept-count: 100
    uri-encoding: utf-8

#spring配置
spring:
  mvc: #文件上传报错处理
    hiddenmethod:
      filter:
        enabled: true
  #mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mango_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&tinyInt1isBit=false
    username: root
    password: Abc1753163342@
    # 配置druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        url-pattern: /druid/*
      aop-patterns: cn.sky1998.mango.mangoApplication
      filters: stat,wall
  #redis配置
  redis:
    host: localhost
    port: 6379
    database: 15
    password: zfb123
    lettuce:
      pool:
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle:  8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 日志配置
logging:
  level:
    com.sky1998: debug
