### 用户列表
GET {{host}}/work/test/list
Accept: */*
Content-Encoding: utf-8
Content-Type: application/json
Authorization: {{token}}

{

}

### 用户列表
GET {{host}}/work/notice/2
Accept: */*
Content-Encoding: utf-8
Content-Type: application/json
Authorization: {{token}}

{

}