
### 新增菜单
POST {{host}}/system/menu/add
Accept: */*
Content-Encoding: utf-8
Content-Type: application/json
Authorization: {{token}}

{

}
### 更新菜单
POST {{host}}/system/menu/remove
Accept: */*
Content-Encoding: utf-8
Content-Type: application/json
Authorization: {{token}}

{

}
###获取菜单列表根据用户
POST {{host}}/system/menu/getMenuByUser
Accept: */*
Content-Encoding: utf-8
Content-Type: application/json
Authorization: {{token}}

{
  "id": 3
}
### 获取菜单列表
POST {{host}}/system/menu/getList
Accept: */*
Content-Encoding: utf-8
Content-Type: application/json
Authorization: {{token}}

{

}


###获取菜单列表根据角色
POST {{host}}/system/menu/getListByRole
Accept: */*
Content-Encoding: utf-8
Content-Type: application/json
Authorization: {{token}}

{

}


###获取菜单列表根据角色
POST {{host}}/system/menu/tree
Accept: */*
Content-Encoding: utf-8
Content-Type: application/json
Authorization: {{token}}

{

}

###获取菜单列表详情
POST {{host}}/system/menu/getDetail
Accept: */*
Content-Encoding: utf-8
Content-Type: application/json
Authorization: {{token}}

{

  "id": 2
}